apiVersion: v1
kind: Service
metadata:
  name: python-guestbook-backend
  labels:
    app: python-guestbook
    tier: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: python-guestbook-backend
  ports:
    - port: 8080
      targetPort: http-server
