apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-guestbook-backend
  labels:
    app.kubernetes.io/name: python-guestbook-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: python-guestbook-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-guestbook-backend
    spec:
      initContainers:
        - name: init-db-ready
          image: localhost:5000/mongo:4
          command: ["/bin/sh", "-c"]
          args:
            - echo "Waiting for mongodb at python-guestbook-mongodb:27017 to go live before the BE...";
            - until (mongo --host python-guestbook-mongodb:27017 >/dev/null) do echo "Waiting for connection for 2 sec."; sleep 2; done
      containers:
        - name: backend
          image: localhost:5000/python-guestbook-backend
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: python-guestbook-backend
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://k8s-monitoring-alloy-receiver.monitoring:4317"
            - name: PORT
              value: "8080"
            - name: GUESTBOOK_DB_ADDR
              value: "python-guestbook-mongodb:27017"
