env-common: &env-common
  name: OTEL_EXPORTER_OTLP_ENDPOINT
  value: "http://k8s-monitoring-alloy-receiver.monitoring:4317"

resources:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: python-guestbook-backend
      labels:
        app.kubernetes.io/name: python-guestbook-backend
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: python-guestbook-backend
      template:
        metadata:
          labels:
            app.kubernetes.io/name: python-guestbook-backend
        spec:
          initContainers:
            - name: init-db-ready
              image: localhost:5000/mongo:4
              command: ["/bin/sh", "-c"]
              args:
                - echo "Waiting for mongodb at python-guestbook-mongodb:27017 to go live before the BE...";
                - until (mongo --host python-guestbook-mongodb:27017 >/dev/null) do echo "Waiting for connection for 2 sec."; sleep 2; done
          containers:
            - name: backend
              image: localhost:5000/python-guestbook-backend
              imagePullPolicy: Always
              ports:
                - name: http-server
                  containerPort: 8080
              env:
                - <<: *env-common
                - name: SERVICE_NAME
                  value: python-guestbook-backend
                - name: PORT
                  value: "8080"
                - name: GUESTBOOK_DB_ADDR
                  value: "python-guestbook-mongodb:27017"
  - apiVersion: v1
    kind: Service
    metadata:
      name: python-guestbook-backend
      labels:
        app: python-guestbook
        tier: backend
    spec:
      type: ClusterIP
      selector:
        app.kubernetes.io/name: python-guestbook-backend
      ports:
        - port: 8080
          targetPort: http-server
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: python-guestbook-mongodb
      labels:
        app: python-guestbook
        tier: db
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: python-guestbook
          tier: db
      template:
        metadata:
          labels:
            app: python-guestbook
            tier: db
        spec:
          containers:
            - name: mongo
              image: localhost:5000/mongo:4
              ports:
                - containerPort: 27017
  - apiVersion: v1
    kind: Service
    metadata:
      name: python-guestbook-mongodb
      labels:
        app: python-guestbook
        tier: db
    spec:
      ports:
        - port: 27017
          targetPort: 27017
      selector:
        app: python-guestbook
        tier: db
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: python-guestbook-frontend
    spec:
      rules:
        - host: localhost
          http:
            paths:
              - pathType: Prefix
                path: "/"
                backend:
                  service:
                    name: python-guestbook-frontend
                    port:
                      number: 80
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: python-guestbook-frontend
      labels:
        app.kubernetes.io/name: python-guestbook-frontend
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: python-guestbook-frontend

      template:
        metadata:
          labels:
            app.kubernetes.io/name: python-guestbook-frontend
        spec:
          containers:
            - name: frontend
              image: localhost:5000/python-guestbook-frontend
              imagePullPolicy: Always
              ports:
                - name: http-server
                  containerPort: 8080
              env:
                - <<: *env-common
                - name: SERVICE_NAME
                  value: python-guestbook-frontend
                - name: PORT
                  value: "8080"
                - name: GUESTBOOK_API_ADDR
                  value: python-guestbook-backend:8080
  - apiVersion: v1
    kind: Service
    metadata:
      name: python-guestbook-frontend
      labels:
        app: python-guestbook
        tier: frontend
    spec:
      type: ClusterIP
      selector:
        app.kubernetes.io/name: python-guestbook-frontend
      ports:
        - port: 80
          targetPort: http-server
