apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: python-guestbook
    tier: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.backend.serviceName }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http-server
      protocol: TCP
