{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  rules:
  - host: {{ .Values.frontend.ingress.host }}
    http:
      paths:
      - pathType: {{ .Values.frontend.ingress.pathType }}
        path: {{ .Values.frontend.ingress.path }}
        backend:
          service:
            name: {{ .Release.Name }}-frontend
            port:
              number: {{ .Values.frontend.service.port }}
{{- end }}
