apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: python-guestbook
    tier: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.frontend.serviceName }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http-server
      protocol: TCP
